### ISSUE TITLE
Unhandled Exception: System.Exception: num_sounds <= IN_sound_num (CAR_TRANNY.abk from Carbon)

### ISSUE THREAD

**Issue by trackmaniamatt** [CrabJournal/ABK_Insert#3]
Hello! I've been testing out v3.0, and I'm getting an error upon trying to insert a second sound file to the car_tranny.abk file from Carbon. This is my output:

J:\All NFS Tools and Utilities\ABK_Insert>ABK_Insert car_tranny.abk CAR_TRANNY_01.wav 1
Bank format: S10A
Sounds: 2

J:\All NFS Tools and Utilities\ABK_Insert>ABK_Insert car_tranny.abk CAR_TRANNY_02.wav 2
Bank format: S10A
Sounds: 2

Unhandled Exception: System.Exception: num_sounds <= IN_sound_num
   at ABK_insert.Program.InsertInS10A(BinaryReader IN_ABK_FILE_Reader, BinaryWriter OUT_ABK_Writer, Int32 IN_sound_num, Int32 ABK_sfxbanksize, String[] args)
   at ABK_insert.Program.Main(String[] args)

I'm not entirely sure if it's something that I did wrong, or if it's the tool being weird.

**Comment by CrabJournal** [comment]
Hi, sounds are counted starting from zero as decoder do, so there's 2 sounds: 0 and 1.

**Comment by trackmaniamatt** [comment]
That makes so much sense. I didn't think I was using it incorrectly, LOL. Thanks for the heads up! :)

**Comment by RAZORXKHARA33** [comment]
The procedure that ABK_insert uses for adding to S10A-formatted banks is different from BNKL-formatted ones. A BNKL typically has a blank sample at the start (dead space, if you will). This gets counted by Sound eXchange but doesn't result in a sound output. This is why you start from 1 instead of 0 when inserting new samples into a BNKL-formatted ABK. ABKs that use the S10A format don't do this, so you start from 0.

Anyway, looks like this was solved fairly quickly. @trackmaniamatt You should be able to close this.
